version: '3.8'

services:
  zookeeper:
    # mem_limit: 1g
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend

  kafka:
    # mem_limit: 4g
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - backend
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local_docker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - backend

# activate this block if you want to run the service via docker-compose
#   core-service:
#     # mem_limit: 2g
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: core-service
#     depends_on:
#         db:
#           condition: service_healthy
#         kafka:
#           condition: service_healthy
#     ports:
#       - "5000:5000"  # Change this to match your app's port
#     environment:
#       - POSTGRES_URI=postgresql://myuser:mypassword@db:5432/mydatabase
#       - KAFKA_URI=kafka:9092
#     networks:
#       - backend

volumes:
  postgres_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  backend:
    driver: bridge